# Generated by Django 2.2.4 on 2019-10-05 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('album_title', models.CharField(max_length=500)),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('Metal', 'Metal'), ('Romantic', 'Romantic'), ('Heavy Metal', 'Heavy Metal'), ('Jazz', 'Jazz'), ('Folk', 'Folk'), ('Rap', 'Rap')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('album_title', 'artist', 'user')},
            },
        ),
    ]
