# Generated by Django 2.2.4 on 2019-10-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
