# Generated by Django 2.2.4 on 2019-10-17 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_auto_20191017_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
