# Generated by Django 2.2.4 on 2019-10-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0006_auto_20191016_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
