# Generated by Django 2.2.4 on 2019-10-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_account_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
